# Generated by Django 6.0.6 on 2026-06-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtenant_code", models.CharField(max_length=50, unique=True)),
                ("tenant_name", models.CharField(max_length=255)),
                ("legal_entity_name", models.CharField(max_length=255)),
                ("trade_license_number", models.CharField(blank=True, max_length=100)),
                ("trade_license_expiry_date", models.DateField(blank=True, null=True)),
                ("passport_number", models.CharField(blank=True, max_length=100)),
                ("emirates_id", models.CharField(blank=True, max_length=100)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("vat_number", models.CharField(blank=True, max_length=100)),
                ("trn_number", models.CharField(blank=True, max_length=100)),
                ("business_activity", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expiring", "Expiring"),
                            ("vacant", "Vacant"),
                            ("terminated", "Terminated"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.internaltenantcompany",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.propertyunit",
                    ),
                ),
            ],
        ),
    ]
