# Generated by Django 6.0.6 on 2026-06-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_code", models.CharField(max_length=50, unique=True)),
                ("property_name", models.CharField(max_length=255)),
                ("plot_number", models.CharField(blank=True, max_length=100)),
                ("zone", models.CharField(blank=True, max_length=100)),
                ("emirate", models.CharField(default="Dubai", max_length=100)),
                ("location_description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "Warehouse"),
                            ("plot", "Plot"),
                            ("office", "Office"),
                            ("yard", "Yard"),
                            ("showroom", "Showroom"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("leased", "Leased"),
                            ("owned", "Owned"),
                            ("managed", "Managed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area_sqft", models.DecimalField(decimal_places=2, max_digits=15)),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "annual_main_rent",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("rent_currency", models.CharField(default="AED", max_length=10)),
                ("main_lease_start_date", models.DateField()),
                ("main_lease_end_date", models.DateField()),
                ("main_lease_notice_days", models.IntegerField(default=90)),
                ("ejari_required", models.BooleanField(default=True)),
                (
                    "municipality_account_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("dewa_account_number", models.CharField(blank=True, max_length=100)),
                ("sewage_account_number", models.CharField(blank=True, max_length=100)),
                ("water_account_number", models.CharField(blank=True, max_length=100)),
                ("access_card_count", models.IntegerField(default=0)),
                ("parking_count", models.IntegerField(default=0)),
                ("loading_bays_count", models.IntegerField(default=0)),
                (
                    "power_capacity_kw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fire_certificate_required", models.BooleanField(default=True)),
                (
                    "fire_certificate_expiry_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expiring", "Expiring"),
                            ("expired", "Expired"),
                            ("vacant", "Vacant"),
                            ("under_renovation", "Under Renovation"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="companies.internaltenantcompany",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_code", models.CharField(max_length=50)),
                ("unit_name", models.CharField(max_length=255)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("warehouse", "Warehouse"),
                            ("office", "Office"),
                            ("yard", "Yard"),
                            ("room", "Room"),
                            ("plot_segment", "Plot Segment"),
                            ("mezzanine", "Mezzanine"),
                            ("parking", "Parking"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("floor_level", models.CharField(blank=True, max_length=50)),
                ("area_sqft", models.DecimalField(decimal_places=2, max_digits=15)),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "rentable_area_sqft",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("reserved", "Reserved"),
                            ("occupied", "Occupied"),
                            ("blocked", "Blocked"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                (
                    "utility_meter_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("fire_zone", models.CharField(blank=True, max_length=100)),
                ("max_occupancy", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "unique_together": {("property", "unit_code")},
            },
        ),
    ]
