# Generated by Django 6.0.6 on 2026-06-10 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_object_id", models.PositiveIntegerField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lease", "Lease Agreement"),
                            ("ejari", "Ejari Certificate"),
                            ("trade_license", "Trade License"),
                            ("id_copy", "ID Copy"),
                            ("passport_copy", "Passport Copy"),
                            ("invoice", "Invoice"),
                            ("receipt", "Receipt"),
                            ("approval", "Approval"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expiring", "Expiring"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
