# Generated by Django 6.0.6 on 2026-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalTenantCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_code", models.CharField(max_length=50, unique=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("tenant_number_drec", models.CharField(blank=True, max_length=100)),
                ("emirate", models.CharField(default="Dubai", max_length=100)),
                ("country", models.CharField(default="UAE", max_length=100)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_issue_date", models.DateField(blank=True, null=True)),
                ("license_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "rera_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("vat_registered", models.BooleanField(default=False)),
                ("vat_number", models.CharField(blank=True, max_length=100)),
                ("trn_number", models.CharField(blank=True, max_length=100)),
                ("office_address", models.TextField(blank=True)),
                ("po_box", models.CharField(blank=True, max_length=50)),
                ("contact_person_name", models.CharField(blank=True, max_length=255)),
                ("contact_person_phone", models.CharField(blank=True, max_length=50)),
                ("contact_person_email", models.EmailField(blank=True, max_length=254)),
                ("company_owner_name", models.CharField(blank=True, max_length=255)),
                ("company_owner_phone", models.CharField(blank=True, max_length=50)),
                ("company_owner_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Internal Tenant Companies",
            },
        ),
    ]
