# Generated by Django 6.0.6 on 2026-06-10 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("properties", "0001_initial"),
        ("subtenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drec_landlord_name",
                    models.CharField(default="DREC", max_length=255),
                ),
                ("drec_tenant_number", models.CharField(max_length=100)),
                (
                    "lease_reference_number",
                    models.CharField(max_length=100, unique=True),
                ),
                ("lease_start_date", models.DateField()),
                ("lease_end_date", models.DateField()),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "rent_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semiannual", "Semiannual"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("payment_terms", models.TextField(blank=True)),
                ("renewal_notice_days", models.IntegerField(default=90)),
                ("grace_period_days", models.IntegerField(default=0)),
                ("ejari_required", models.BooleanField(default=True)),
                ("ejari_number", models.CharField(blank=True, max_length=100)),
                ("ejari_issue_date", models.DateField(blank=True, null=True)),
                ("ejari_expiry_date", models.DateField(blank=True, null=True)),
                ("signed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("expiring", "Expiring"),
                            ("expired", "Expired"),
                            ("renewed", "Renewed"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("renewal_stage", models.CharField(blank=True, max_length=100)),
                ("legal_notes", models.TextField(blank=True)),
                ("finance_notes", models.TextField(blank=True)),
                ("document_folder", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.internaltenantcompany",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_leases",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sublease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sublease_reference", models.CharField(max_length=100, unique=True)),
                ("lease_start_date", models.DateField()),
                ("lease_end_date", models.DateField()),
                ("contract_signed_date", models.DateField(blank=True, null=True)),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "service_charge_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("payment_frequency", models.CharField(max_length=50)),
                ("payment_due_day", models.IntegerField(default=1)),
                ("notice_days", models.IntegerField(default=60)),
                ("grace_period_days", models.IntegerField(default=0)),
                ("late_fee_policy", models.TextField(blank=True)),
                (
                    "renewal_option",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("manual", "Manual"),
                            ("none", "None"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("ejari_required", models.BooleanField(default=True)),
                ("ejari_number", models.CharField(blank=True, max_length=100)),
                ("ejari_issue_date", models.DateField(blank=True, null=True)),
                ("ejari_expiry_date", models.DateField(blank=True, null=True)),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("move_out_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expiring", "Expiring"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                            ("vacated", "Vacated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "occupancy_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_subleases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.internaltenantcompany",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
                (
                    "subtenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subtenants.subtenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertyunit",
                    ),
                ),
            ],
        ),
    ]
